// Comprehensive player + team index for search — all major pro sports, March 2026

export type SearchTeam = {
  name: string;
  league: "NBA" | "NFL" | "MLB" | "MLS" | "NHL";
  abbr: string;
  rank: string;
  city?: string;
};

export type SearchPlayer = {
  name: string;
  team: string;
  league: "NBA" | "NFL" | "MLB" | "MLS" | "NHL";
  position: string;
  stat: string;
  number?: string;
};

// ─── ALL NBA TEAMS ────────────────────────────────────────────────────────────
export const NBA_TEAMS: SearchTeam[] = [
  { name: "Atlanta Hawks", league: "NBA", abbr: "ATL", rank: "8th East" },
  { name: "Boston Celtics", league: "NBA", abbr: "BOS", rank: "2nd East" },
  { name: "Brooklyn Nets", league: "NBA", abbr: "BKN", rank: "14th East" },
  { name: "Charlotte Hornets", league: "NBA", abbr: "CHA", rank: "10th East" },
  { name: "Chicago Bulls", league: "NBA", abbr: "CHI", rank: "11th East" },
  { name: "Cleveland Cavaliers", league: "NBA", abbr: "CLE", rank: "4th East" },
  { name: "Dallas Mavericks", league: "NBA", abbr: "DAL", rank: "11th West" },
  { name: "Denver Nuggets", league: "NBA", abbr: "DEN", rank: "6th West" },
  { name: "Detroit Pistons", league: "NBA", abbr: "DET", rank: "1st East" },
  { name: "Golden State Warriors", league: "NBA", abbr: "GSW", rank: "10th West" },
  { name: "Houston Rockets", league: "NBA", abbr: "HOU", rank: "5th West" },
  { name: "Indiana Pacers", league: "NBA", abbr: "IND", rank: "3rd East" },
  { name: "Los Angeles Clippers", league: "NBA", abbr: "LAC", rank: "8th West" },
  { name: "Los Angeles Lakers", league: "NBA", abbr: "LAL", rank: "3rd West" },
  { name: "Memphis Grizzlies", league: "NBA", abbr: "MEM", rank: "12th West" },
  { name: "Miami Heat", league: "NBA", abbr: "MIA", rank: "7th East" },
  { name: "Milwaukee Bucks", league: "NBA", abbr: "MIL", rank: "5th East" },
  { name: "Minnesota Timberwolves", league: "NBA", abbr: "MIN", rank: "4th West" },
  { name: "New Orleans Pelicans", league: "NBA", abbr: "NOP", rank: "13th West" },
  { name: "New York Knicks", league: "NBA", abbr: "NYK", rank: "3rd East" },
  { name: "Oklahoma City Thunder", league: "NBA", abbr: "OKC", rank: "1st West" },
  { name: "Orlando Magic", league: "NBA", abbr: "ORL", rank: "6th East" },
  { name: "Philadelphia 76ers", league: "NBA", abbr: "PHI", rank: "9th East" },
  { name: "Phoenix Suns", league: "NBA", abbr: "PHX", rank: "7th West" },
  { name: "Portland Trail Blazers", league: "NBA", abbr: "POR", rank: "9th West" },
  { name: "Sacramento Kings", league: "NBA", abbr: "SAC", rank: "14th West" },
  { name: "San Antonio Spurs", league: "NBA", abbr: "SAS", rank: "2nd West" },
  { name: "Toronto Raptors", league: "NBA", abbr: "TOR", rank: "12th East" },
  { name: "Utah Jazz", league: "NBA", abbr: "UTA", rank: "15th West" },
  { name: "Washington Wizards", league: "NBA", abbr: "WAS", rank: "13th East" },
];

// ─── ALL NFL TEAMS ────────────────────────────────────────────────────────────
export const NFL_TEAMS: SearchTeam[] = [
  { name: "Arizona Cardinals", league: "NFL", abbr: "ARI", rank: "NFC West" },
  { name: "Atlanta Falcons", league: "NFL", abbr: "ATL", rank: "NFC South" },
  { name: "Baltimore Ravens", league: "NFL", abbr: "BAL", rank: "AFC North" },
  { name: "Buffalo Bills", league: "NFL", abbr: "BUF", rank: "AFC East Champs" },
  { name: "Carolina Panthers", league: "NFL", abbr: "CAR", rank: "NFC South" },
  { name: "Chicago Bears", league: "NFL", abbr: "CHI", rank: "NFC North" },
  { name: "Cincinnati Bengals", league: "NFL", abbr: "CIN", rank: "AFC North" },
  { name: "Cleveland Browns", league: "NFL", abbr: "CLE", rank: "AFC North" },
  { name: "Dallas Cowboys", league: "NFL", abbr: "DAL", rank: "NFC East" },
  { name: "Denver Broncos", league: "NFL", abbr: "DEN", rank: "AFC West" },
  { name: "Detroit Lions", league: "NFL", abbr: "DET", rank: "NFC North Champs" },
  { name: "Green Bay Packers", league: "NFL", abbr: "GB", rank: "NFC North" },
  { name: "Houston Texans", league: "NFL", abbr: "HOU", rank: "AFC South Champs" },
  { name: "Indianapolis Colts", league: "NFL", abbr: "IND", rank: "AFC South" },
  { name: "Jacksonville Jaguars", league: "NFL", abbr: "JAX", rank: "AFC South" },
  { name: "Kansas City Chiefs", league: "NFL", abbr: "KC", rank: "Super Bowl LIX Champs" },
  { name: "Las Vegas Raiders", league: "NFL", abbr: "LV", rank: "AFC West" },
  { name: "Los Angeles Chargers", league: "NFL", abbr: "LAC", rank: "AFC West" },
  { name: "Los Angeles Rams", league: "NFL", abbr: "LAR", rank: "NFC West" },
  { name: "Miami Dolphins", league: "NFL", abbr: "MIA", rank: "AFC East" },
  { name: "Minnesota Vikings", league: "NFL", abbr: "MIN", rank: "NFC North" },
  { name: "New England Patriots", league: "NFL", abbr: "NE", rank: "AFC East" },
  { name: "New Orleans Saints", league: "NFL", abbr: "NO", rank: "NFC South" },
  { name: "New York Giants", league: "NFL", abbr: "NYG", rank: "NFC East" },
  { name: "New York Jets", league: "NFL", abbr: "NYJ", rank: "AFC East" },
  { name: "Philadelphia Eagles", league: "NFL", abbr: "PHI", rank: "NFC East Champs" },
  { name: "Pittsburgh Steelers", league: "NFL", abbr: "PIT", rank: "AFC North" },
  { name: "San Francisco 49ers", league: "NFL", abbr: "SF", rank: "NFC West" },
  { name: "Seattle Seahawks", league: "NFL", abbr: "SEA", rank: "NFC West" },
  { name: "Tampa Bay Buccaneers", league: "NFL", abbr: "TB", rank: "NFC South" },
  { name: "Tennessee Titans", league: "NFL", abbr: "TEN", rank: "AFC South" },
  { name: "Washington Commanders", league: "NFL", abbr: "WAS", rank: "NFC East" },
];

// ─── ALL MLB TEAMS ────────────────────────────────────────────────────────────
export const MLB_TEAMS: SearchTeam[] = [
  { name: "Arizona Diamondbacks", league: "MLB", abbr: "ARI", rank: "NL West" },
  { name: "Atlanta Braves", league: "MLB", abbr: "ATL", rank: "NL East" },
  { name: "Baltimore Orioles", league: "MLB", abbr: "BAL", rank: "AL East" },
  { name: "Boston Red Sox", league: "MLB", abbr: "BOS", rank: "AL East" },
  { name: "Chicago Cubs", league: "MLB", abbr: "CHC", rank: "NL Central" },
  { name: "Chicago White Sox", league: "MLB", abbr: "CWS", rank: "AL Central" },
  { name: "Cincinnati Reds", league: "MLB", abbr: "CIN", rank: "NL Central" },
  { name: "Cleveland Guardians", league: "MLB", abbr: "CLE", rank: "AL Central" },
  { name: "Colorado Rockies", league: "MLB", abbr: "COL", rank: "NL West" },
  { name: "Detroit Tigers", league: "MLB", abbr: "DET", rank: "AL Central" },
  { name: "Houston Astros", league: "MLB", abbr: "HOU", rank: "AL West" },
  { name: "Kansas City Royals", league: "MLB", abbr: "KC", rank: "AL Central" },
  { name: "Los Angeles Angels", league: "MLB", abbr: "LAA", rank: "AL West" },
  { name: "Los Angeles Dodgers", league: "MLB", abbr: "LAD", rank: "NL West" },
  { name: "Miami Marlins", league: "MLB", abbr: "MIA", rank: "NL East" },
  { name: "Milwaukee Brewers", league: "MLB", abbr: "MIL", rank: "NL Central" },
  { name: "Minnesota Twins", league: "MLB", abbr: "MIN", rank: "AL Central" },
  { name: "New York Mets", league: "MLB", abbr: "NYM", rank: "NL East" },
  { name: "New York Yankees", league: "MLB", abbr: "NYY", rank: "AL East" },
  { name: "Oakland Athletics", league: "MLB", abbr: "OAK", rank: "AL West" },
  { name: "Philadelphia Phillies", league: "MLB", abbr: "PHI", rank: "NL East" },
  { name: "Pittsburgh Pirates", league: "MLB", abbr: "PIT", rank: "NL Central" },
  { name: "San Diego Padres", league: "MLB", abbr: "SD", rank: "NL West" },
  { name: "San Francisco Giants", league: "MLB", abbr: "SF", rank: "NL West" },
  { name: "Seattle Mariners", league: "MLB", abbr: "SEA", rank: "AL West" },
  { name: "St. Louis Cardinals", league: "MLB", abbr: "STL", rank: "NL Central" },
  { name: "Tampa Bay Rays", league: "MLB", abbr: "TB", rank: "AL East" },
  { name: "Texas Rangers", league: "MLB", abbr: "TEX", rank: "AL West" },
  { name: "Toronto Blue Jays", league: "MLB", abbr: "TOR", rank: "AL East" },
  { name: "Washington Nationals", league: "MLB", abbr: "WAS", rank: "NL East" },
];

// ─── ALL MLS TEAMS ────────────────────────────────────────────────────────────
export const MLS_TEAMS: SearchTeam[] = [
  { name: "Atlanta United", league: "MLS", abbr: "ATL", rank: "Eastern Conference" },
  { name: "Austin FC", league: "MLS", abbr: "ATX", rank: "Western Conference" },
  { name: "Charlotte FC", league: "MLS", abbr: "CLT", rank: "Eastern Conference" },
  { name: "Chicago Fire", league: "MLS", abbr: "CHI", rank: "Eastern Conference" },
  { name: "FC Cincinnati", league: "MLS", abbr: "CIN", rank: "Eastern Conference" },
  { name: "FC Dallas", league: "MLS", abbr: "DAL", rank: "Western Conference" },
  { name: "Colorado Rapids", league: "MLS", abbr: "COL", rank: "Western Conference" },
  { name: "Columbus Crew", league: "MLS", abbr: "CLB", rank: "Eastern Conference" },
  { name: "D.C. United", league: "MLS", abbr: "DC", rank: "Eastern Conference" },
  { name: "Houston Dynamo", league: "MLS", abbr: "HOU", rank: "3rd West" },
  { name: "Inter Miami CF", league: "MLS", abbr: "MIA", rank: "Eastern Conference" },
  { name: "LA Galaxy", league: "MLS", abbr: "LAG", rank: "Western Conference" },
  { name: "Los Angeles FC", league: "MLS", abbr: "LAFC", rank: "2nd West" },
  { name: "Minnesota United", league: "MLS", abbr: "MIN", rank: "Western Conference" },
  { name: "CF Montréal", league: "MLS", abbr: "MTL", rank: "Eastern Conference" },
  { name: "Nashville SC", league: "MLS", abbr: "NSH", rank: "Eastern Conference" },
  { name: "New England Revolution", league: "MLS", abbr: "NE", rank: "1st East" },
  { name: "New York City FC", league: "MLS", abbr: "NYC", rank: "Eastern Conference" },
  { name: "New York Red Bulls", league: "MLS", abbr: "NYRB", rank: "Eastern Conference" },
  { name: "Orlando City", league: "MLS", abbr: "ORL", rank: "Eastern Conference" },
  { name: "Philadelphia Union", league: "MLS", abbr: "PHI", rank: "Eastern Conference" },
  { name: "Portland Timbers", league: "MLS", abbr: "POR", rank: "Western Conference" },
  { name: "Real Salt Lake", league: "MLS", abbr: "RSL", rank: "Western Conference" },
  { name: "San Diego FC", league: "MLS", abbr: "SD", rank: "Western Conference" },
  { name: "San Jose Earthquakes", league: "MLS", abbr: "SJ", rank: "Western Conference" },
  { name: "Seattle Sounders", league: "MLS", abbr: "SEA", rank: "Western Conference" },
  { name: "Sporting Kansas City", league: "MLS", abbr: "SKC", rank: "Western Conference" },
  { name: "St. Louis City SC", league: "MLS", abbr: "STL", rank: "Western Conference" },
  { name: "Toronto FC", league: "MLS", abbr: "TOR", rank: "Eastern Conference" },
  { name: "Vancouver Whitecaps", league: "MLS", abbr: "VAN", rank: "1st West" },
];

export const ALL_TEAMS: SearchTeam[] = [
  ...NBA_TEAMS,
  ...NFL_TEAMS,
  ...MLB_TEAMS,
  ...MLS_TEAMS,
];

// ─── ALL NBA PLAYERS ──────────────────────────────────────────────────────────
export const NBA_PLAYERS: SearchPlayer[] = [
  // Atlanta Hawks
  { name: "Trae Young", team: "Atlanta Hawks", league: "NBA", position: "PG", stat: "26.4 PPG, 10.8 APG", number: "11" },
  { name: "Jalen Johnson", team: "Atlanta Hawks", league: "NBA", position: "SF", stat: "18.4 PPG, 8.2 REB", number: "1" },
  { name: "De'Andre Hunter", team: "Atlanta Hawks", league: "NBA", position: "SF", stat: "14.2 PPG", number: "12" },
  { name: "Clint Capela", team: "Atlanta Hawks", league: "NBA", position: "C", stat: "10.8 PPG, 10.4 REB", number: "15" },
  { name: "Dyson Daniels", team: "Atlanta Hawks", league: "NBA", position: "SG", stat: "12.8 PPG, 2.4 STL", number: "5" },
  { name: "Bogdan Bogdanović", team: "Atlanta Hawks", league: "NBA", position: "SG", stat: "12.1 PPG", number: "13" },
  { name: "Larry Nance Jr.", team: "Atlanta Hawks", league: "NBA", position: "PF", stat: "8.4 PPG, 7.1 REB", number: "22" },
  // Boston Celtics
  { name: "Jayson Tatum", team: "Boston Celtics", league: "NBA", position: "SF/PF", stat: "27.1 PPG, 8.9 REB", number: "0" },
  { name: "Jaylen Brown", team: "Boston Celtics", league: "NBA", position: "SG/SF", stat: "23.8 PPG, 5.5 REB", number: "7" },
  { name: "Kristaps Porzingis", team: "Boston Celtics", league: "NBA", position: "C", stat: "18.8 PPG, 1.9 BLK", number: "8" },
  { name: "Jrue Holiday", team: "Boston Celtics", league: "NBA", position: "PG/SG", stat: "12.8 PPG, 5.1 APG", number: "4" },
  { name: "Al Horford", team: "Boston Celtics", league: "NBA", position: "C/PF", stat: "9.4 PPG, 6.2 REB", number: "42" },
  { name: "Payton Pritchard", team: "Boston Celtics", league: "NBA", position: "PG", stat: "14.2 PPG, 40.8% 3P", number: "11" },
  { name: "Sam Hauser", team: "Boston Celtics", league: "NBA", position: "SF", stat: "11.8 PPG, 42.1% 3P", number: "30" },
  // Brooklyn Nets
  { name: "Cam Thomas", team: "Brooklyn Nets", league: "NBA", position: "SG", stat: "24.8 PPG", number: "5" },
  { name: "Nic Claxton", team: "Brooklyn Nets", league: "NBA", position: "C", stat: "11.4 PPG, 8.8 REB", number: "33" },
  { name: "Dorian Finney-Smith", team: "Brooklyn Nets", league: "NBA", position: "SF", stat: "10.2 PPG", number: "28" },
  { name: "Noah Clowney", team: "Brooklyn Nets", league: "NBA", position: "PF", stat: "9.8 PPG, 7.2 REB", number: "21" },
  { name: "Trendon Watford", team: "Brooklyn Nets", league: "NBA", position: "SF", stat: "8.4 PPG", number: "2" },
  // Charlotte Hornets
  { name: "LaMelo Ball", team: "Charlotte Hornets", league: "NBA", position: "PG", stat: "27.4 PPG, 8.2 APG", number: "1" },
  { name: "Brandon Miller", team: "Charlotte Hornets", league: "NBA", position: "SF", stat: "20.1 PPG", number: "24" },
  { name: "Miles Bridges", team: "Charlotte Hornets", league: "NBA", position: "PF", stat: "18.4 PPG, 7.8 REB", number: "0" },
  { name: "Mark Williams", team: "Charlotte Hornets", league: "NBA", position: "C", stat: "12.8 PPG, 9.4 REB", number: "5" },
  { name: "Grant Williams", team: "Charlotte Hornets", league: "NBA", position: "PF", stat: "9.8 PPG", number: "2" },
  // Chicago Bulls
  { name: "Zach LaVine", team: "Chicago Bulls", league: "NBA", position: "SG", stat: "22.4 PPG, 4.8 APG", number: "8" },
  { name: "Nikola Vucevic", team: "Chicago Bulls", league: "NBA", position: "C", stat: "16.8 PPG, 10.8 REB", number: "9" },
  { name: "Coby White", team: "Chicago Bulls", league: "NBA", position: "PG/SG", stat: "19.8 PPG", number: "0" },
  { name: "Patrick Williams", team: "Chicago Bulls", league: "NBA", position: "SF/PF", stat: "13.4 PPG", number: "44" },
  { name: "Josh Giddey", team: "Chicago Bulls", league: "NBA", position: "PG", stat: "14.2 PPG, 7.8 REB", number: "3" },
  // Cleveland Cavaliers
  { name: "Donovan Mitchell", team: "Cleveland Cavaliers", league: "NBA", position: "SG", stat: "26.9 PPG", number: "45" },
  { name: "Evan Mobley", team: "Cleveland Cavaliers", league: "NBA", position: "C/PF", stat: "20.4 PPG, 10.1 REB", number: "4" },
  { name: "Darius Garland", team: "Cleveland Cavaliers", league: "NBA", position: "PG", stat: "21.4 PPG, 8.8 APG", number: "10" },
  { name: "Jarrett Allen", team: "Cleveland Cavaliers", league: "NBA", position: "C", stat: "11.2 PPG, 9.8 REB", number: "31" },
  { name: "Max Strus", team: "Cleveland Cavaliers", league: "NBA", position: "SG/SF", stat: "12.4 PPG", number: "1" },
  { name: "Sam Merrill", team: "Cleveland Cavaliers", league: "NBA", position: "SG", stat: "10.4 PPG", number: "10" },
  // Dallas Mavericks
  { name: "Kyrie Irving", team: "Dallas Mavericks", league: "NBA", position: "PG", stat: "24.8 PPG, 5.8 APG", number: "11" },
  { name: "P.J. Washington", team: "Dallas Mavericks", league: "NBA", position: "PF", stat: "14.8 PPG", number: "25" },
  { name: "Derrick Jones Jr.", team: "Dallas Mavericks", league: "NBA", position: "SF", stat: "10.4 PPG", number: "55" },
  { name: "Maxi Kleber", team: "Dallas Mavericks", league: "NBA", position: "PF/C", stat: "8.8 PPG", number: "42" },
  { name: "Spencer Dinwiddie", team: "Dallas Mavericks", league: "NBA", position: "PG", stat: "12.4 PPG", number: "26" },
  // Denver Nuggets
  { name: "Nikola Jokić", team: "Denver Nuggets", league: "NBA", position: "C", stat: "26.8 PPG, 12.4 REB, 9.0 APG", number: "15" },
  { name: "Jamal Murray", team: "Denver Nuggets", league: "NBA", position: "PG", stat: "22.4 PPG, 6.8 APG", number: "27" },
  { name: "Michael Porter Jr.", team: "Denver Nuggets", league: "NBA", position: "SF", stat: "18.4 PPG, 6.8 REB", number: "1" },
  { name: "Aaron Gordon", team: "Denver Nuggets", league: "NBA", position: "PF", stat: "14.1 PPG, 6.8 REB", number: "50" },
  { name: "Kentavious Caldwell-Pope", team: "Denver Nuggets", league: "NBA", position: "SG", stat: "10.8 PPG", number: "5" },
  { name: "Reggie Jackson", team: "Denver Nuggets", league: "NBA", position: "PG", stat: "8.4 PPG", number: "7" },
  // Detroit Pistons
  { name: "Cade Cunningham", team: "Detroit Pistons", league: "NBA", position: "PG", stat: "28.9 PPG, 9.4 APG (injured)", number: "2" },
  { name: "Jaden Ivey", team: "Detroit Pistons", league: "NBA", position: "SG", stat: "16.4 PPG, 4.9 APG", number: "23" },
  { name: "Isaiah Stewart", team: "Detroit Pistons", league: "NBA", position: "C/PF", stat: "11.8 PPG, 9.3 REB", number: "28" },
  { name: "Ausar Thompson", team: "Detroit Pistons", league: "NBA", position: "SF", stat: "14.2 PPG, 6.8 REB", number: "5" },
  { name: "James Wiseman", team: "Detroit Pistons", league: "NBA", position: "C", stat: "10.4 PPG, 7.2 REB", number: "13" },
  { name: "Malik Beasley", team: "Detroit Pistons", league: "NBA", position: "SG", stat: "13.1 PPG", number: "5" },
  // Golden State Warriors
  { name: "Stephen Curry", team: "Golden State Warriors", league: "NBA", position: "PG", stat: "26.8 PPG, 43.1% 3P", number: "30" },
  { name: "Andrew Wiggins", team: "Golden State Warriors", league: "NBA", position: "SF", stat: "17.4 PPG", number: "22" },
  { name: "Draymond Green", team: "Golden State Warriors", league: "NBA", position: "PF", stat: "9.4 PPG, 7.8 REB, 7.2 APG", number: "23" },
  { name: "Jonathan Kuminga", team: "Golden State Warriors", league: "NBA", position: "SF/PF", stat: "18.8 PPG", number: "00" },
  { name: "Brandin Podziemski", team: "Golden State Warriors", league: "NBA", position: "SG", stat: "12.4 PPG", number: "2" },
  { name: "Moses Moody", team: "Golden State Warriors", league: "NBA", position: "SG", stat: "9.8 PPG", number: "4" },
  { name: "Trayce Jackson-Davis", team: "Golden State Warriors", league: "NBA", position: "C", stat: "9.4 PPG, 7.1 REB", number: "32" },
  // Houston Rockets
  { name: "Kevin Durant", team: "Houston Rockets", league: "NBA", position: "SF", stat: "23.6 PPG, 6.4 REB", number: "7" },
  { name: "Jalen Green", team: "Houston Rockets", league: "NBA", position: "SG", stat: "22.1 PPG", number: "4" },
  { name: "Amen Thompson", team: "Houston Rockets", league: "NBA", position: "SG/SF", stat: "17.9 PPG, 7.8 REB", number: "1" },
  { name: "Alperen Şengün", team: "Houston Rockets", league: "NBA", position: "C", stat: "19.3 PPG, 8.7 REB", number: "28" },
  { name: "Fred VanVleet", team: "Houston Rockets", league: "NBA", position: "PG", stat: "13.8 PPG, 6.9 APG", number: "5" },
  { name: "Tari Eason", team: "Houston Rockets", league: "NBA", position: "SF/PF", stat: "9.4 PPG, 5.1 REB", number: "17" },
  { name: "Jabari Smith Jr.", team: "Houston Rockets", league: "NBA", position: "PF", stat: "10.2 PPG, 5.8 REB", number: "10" },
  { name: "Dillon Brooks", team: "Houston Rockets", league: "NBA", position: "SF", stat: "11.3 PPG", number: "9" },
  { name: "Cam Whitmore", team: "Houston Rockets", league: "NBA", position: "SG/SF", stat: "8.6 PPG", number: "8" },
  { name: "Steven Adams", team: "Houston Rockets", league: "NBA", position: "C", stat: "6.1 PPG, 9.4 REB", number: "12" },
  // Indiana Pacers
  { name: "Tyrese Haliburton", team: "Indiana Pacers", league: "NBA", position: "PG", stat: "24.4 PPG, 10.9 APG", number: "0" },
  { name: "Pascal Siakam", team: "Indiana Pacers", league: "NBA", position: "PF", stat: "21.8 PPG, 7.8 REB", number: "43" },
  { name: "Myles Turner", team: "Indiana Pacers", league: "NBA", position: "C", stat: "14.4 PPG, 2.2 BLK", number: "33" },
  { name: "Andrew Nembhard", team: "Indiana Pacers", league: "NBA", position: "PG", stat: "12.8 PPG, 5.4 APG", number: "2" },
  { name: "Bennedict Mathurin", team: "Indiana Pacers", league: "NBA", position: "SG/SF", stat: "16.4 PPG", number: "00" },
  { name: "T.J. McConnell", team: "Indiana Pacers", league: "NBA", position: "PG", stat: "9.8 PPG", number: "9" },
  { name: "Isaiah Jackson", team: "Indiana Pacers", league: "NBA", position: "C", stat: "8.4 PPG, 6.8 REB", number: "22" },
  // Los Angeles Clippers
  { name: "Kawhi Leonard", team: "Los Angeles Clippers", league: "NBA", position: "SF", stat: "19.4 PPG, 5.8 REB", number: "2" },
  { name: "Ivica Zubac", team: "Los Angeles Clippers", league: "NBA", position: "C", stat: "12.8 PPG, 10.4 REB", number: "40" },
  { name: "Norman Powell", team: "Los Angeles Clippers", league: "NBA", position: "SG", stat: "19.8 PPG", number: "24" },
  { name: "James Harden", team: "Los Angeles Clippers", league: "NBA", position: "PG", stat: "16.4 PPG, 7.8 APG", number: "1" },
  { name: "Terance Mann", team: "Los Angeles Clippers", league: "NBA", position: "SF", stat: "10.4 PPG", number: "14" },
  // Los Angeles Lakers
  { name: "LeBron James", team: "Los Angeles Lakers", league: "NBA", position: "SF/PF", stat: "24.3 PPG, 8.8 APG", number: "23" },
  { name: "Anthony Davis", team: "Los Angeles Lakers", league: "NBA", position: "C/PF", stat: "24.1 PPG, 12.3 REB", number: "3" },
  { name: "Luka Dončić", team: "Los Angeles Lakers", league: "NBA", position: "PG", stat: "29.8 PPG, 9.2 APG", number: "77" },
  { name: "Austin Reaves", team: "Los Angeles Lakers", league: "NBA", position: "SG", stat: "18.4 PPG, 5.8 APG", number: "15" },
  { name: "Rui Hachimura", team: "Los Angeles Lakers", league: "NBA", position: "SF/PF", stat: "13.9 PPG", number: "28" },
  { name: "Gabe Vincent", team: "Los Angeles Lakers", league: "NBA", position: "PG/SG", stat: "8.4 PPG", number: "7" },
  { name: "Dorian Finney-Smith", team: "Los Angeles Lakers", league: "NBA", position: "SF", stat: "9.8 PPG", number: "18" },
  // Memphis Grizzlies
  { name: "Ja Morant", team: "Memphis Grizzlies", league: "NBA", position: "PG", stat: "26.8 PPG, 8.1 APG", number: "12" },
  { name: "Desmond Bane", team: "Memphis Grizzlies", league: "NBA", position: "SG", stat: "21.4 PPG", number: "22" },
  { name: "Jaren Jackson Jr.", team: "Memphis Grizzlies", league: "NBA", position: "C/PF", stat: "20.4 PPG, 2.4 BLK", number: "13" },
  { name: "Santi Aldama", team: "Memphis Grizzlies", league: "NBA", position: "PF", stat: "12.8 PPG", number: "7" },
  { name: "Vince Williams Jr.", team: "Memphis Grizzlies", league: "NBA", position: "SG/SF", stat: "9.4 PPG", number: "5" },
  { name: "Luke Kennard", team: "Memphis Grizzlies", league: "NBA", position: "SG", stat: "8.4 PPG", number: "3" },
  // Miami Heat
  { name: "Bam Adebayo", team: "Miami Heat", league: "NBA", position: "C", stat: "20.4 PPG, 10.1 REB", number: "13" },
  { name: "Tyler Herro", team: "Miami Heat", league: "NBA", position: "SG", stat: "24.8 PPG", number: "14" },
  { name: "Terry Rozier", team: "Miami Heat", league: "NBA", position: "PG/SG", stat: "16.8 PPG", number: "0" },
  { name: "Nikola Jović", team: "Miami Heat", league: "NBA", position: "PF", stat: "11.4 PPG", number: "5" },
  { name: "Haywood Highsmith", team: "Miami Heat", league: "NBA", position: "SF", stat: "9.8 PPG", number: "24" },
  { name: "Duncan Robinson", team: "Miami Heat", league: "NBA", position: "SG/SF", stat: "12.4 PPG, 39.8% 3P", number: "55" },
  // Milwaukee Bucks
  { name: "Giannis Antetokounmpo", team: "Milwaukee Bucks", league: "NBA", position: "PF/C", stat: "30.2 PPG, 11.8 REB", number: "34" },
  { name: "Damian Lillard", team: "Milwaukee Bucks", league: "NBA", position: "PG", stat: "22.8 PPG, 7.4 APG", number: "0" },
  { name: "Khris Middleton", team: "Milwaukee Bucks", league: "NBA", position: "SF/PF", stat: "14.8 PPG", number: "22" },
  { name: "Brook Lopez", team: "Milwaukee Bucks", league: "NBA", position: "C", stat: "12.4 PPG, 2.1 BLK", number: "11" },
  { name: "Bobby Portis", team: "Milwaukee Bucks", league: "NBA", position: "PF/C", stat: "14.8 PPG, 7.9 REB", number: "9" },
  { name: "Patrick Beverley", team: "Milwaukee Bucks", league: "NBA", position: "PG", stat: "7.4 PPG", number: "21" },
  // Minnesota Timberwolves
  { name: "Anthony Edwards", team: "Minnesota Timberwolves", league: "NBA", position: "SG", stat: "27.3 PPG (out, knee)", number: "5" },
  { name: "Rudy Gobert", team: "Minnesota Timberwolves", league: "NBA", position: "C", stat: "12.4 PPG, 12.8 REB, 2.4 BLK", number: "27" },
  { name: "Mike Conley", team: "Minnesota Timberwolves", league: "NBA", position: "PG", stat: "10.4 PPG, 6.4 APG", number: "10" },
  { name: "Jaden McDaniels", team: "Minnesota Timberwolves", league: "NBA", position: "SF/PF", stat: "14.8 PPG", number: "3" },
  { name: "Julius Randle", team: "Minnesota Timberwolves", league: "NBA", position: "PF", stat: "18.4 PPG, 8.8 REB", number: "30" },
  { name: "Naz Reid", team: "Minnesota Timberwolves", league: "NBA", position: "C/PF", stat: "12.4 PPG", number: "11" },
  { name: "Rob Dillingham", team: "Minnesota Timberwolves", league: "NBA", position: "PG", stat: "11.8 PPG, 4.2 APG (rookie)", number: "10" },
  { name: "Nickeil Alexander-Walker", team: "Minnesota Timberwolves", league: "NBA", position: "SG", stat: "9.4 PPG", number: "9" },
  { name: "Donte DiVincenzo", team: "Minnesota Timberwolves", league: "NBA", position: "SG", stat: "11.2 PPG", number: "0" },
  // New Orleans Pelicans
  { name: "Zion Williamson", team: "New Orleans Pelicans", league: "NBA", position: "PF", stat: "22.8 PPG, 6.4 REB", number: "1" },
  { name: "CJ McCollum", team: "New Orleans Pelicans", league: "NBA", position: "SG", stat: "18.4 PPG", number: "3" },
  { name: "Herbert Jones", team: "New Orleans Pelicans", league: "NBA", position: "SF", stat: "9.8 PPG", number: "5" },
  { name: "Trey Murphy III", team: "New Orleans Pelicans", league: "NBA", position: "SF", stat: "14.8 PPG", number: "25" },
  { name: "Jose Alvarado", team: "New Orleans Pelicans", league: "NBA", position: "PG", stat: "8.4 PPG, 1.8 STL", number: "15" },
  // New York Knicks
  { name: "Jalen Brunson", team: "New York Knicks", league: "NBA", position: "PG", stat: "26.8 PPG, 6.8 APG", number: "11" },
  { name: "Karl-Anthony Towns", team: "New York Knicks", league: "NBA", position: "C/PF", stat: "24.8 PPG, 13.4 REB", number: "32" },
  { name: "Josh Hart", team: "New York Knicks", league: "NBA", position: "SG/SF", stat: "12.4 PPG, 8.4 REB", number: "3" },
  { name: "OG Anunoby", team: "New York Knicks", league: "NBA", position: "SF/PF", stat: "16.8 PPG", number: "8" },
  { name: "Mikal Bridges", team: "New York Knicks", league: "NBA", position: "SF", stat: "18.4 PPG", number: "25" },
  { name: "Donte DiVincenzo", team: "New York Knicks", league: "NBA", position: "SG", stat: "10.8 PPG", number: "0" },
  // Oklahoma City Thunder
  { name: "Shai Gilgeous-Alexander", team: "Oklahoma City Thunder", league: "NBA", position: "PG", stat: "32.1 PPG, 2.0 STL (MVP fav.)", number: "2" },
  { name: "Jalen Williams", team: "Oklahoma City Thunder", league: "NBA", position: "SG", stat: "23.4 PPG", number: "8" },
  { name: "Chet Holmgren", team: "Oklahoma City Thunder", league: "NBA", position: "C/PF", stat: "17.9 PPG, 2.6 BLK", number: "7" },
  { name: "Luguentz Dort", team: "Oklahoma City Thunder", league: "NBA", position: "SG", stat: "12.4 PPG", number: "5" },
  { name: "Alex Caruso", team: "Oklahoma City Thunder", league: "NBA", position: "PG/SG", stat: "9.8 PPG, 1.8 STL", number: "15" },
  { name: "Isaiah Joe", team: "Oklahoma City Thunder", league: "NBA", position: "SG", stat: "9.1 PPG", number: "11" },
  { name: "Ousmane Dieng", team: "Oklahoma City Thunder", league: "NBA", position: "SF", stat: "7.8 PPG", number: "13" },
  // Orlando Magic
  { name: "Paolo Banchero", team: "Orlando Magic", league: "NBA", position: "PF", stat: "24.2 PPG", number: "5" },
  { name: "Franz Wagner", team: "Orlando Magic", league: "NBA", position: "SF/PF", stat: "21.8 PPG", number: "22" },
  { name: "Wendell Carter Jr.", team: "Orlando Magic", league: "NBA", position: "C", stat: "12.4 PPG, 8.8 REB", number: "34" },
  { name: "Jalen Suggs", team: "Orlando Magic", league: "NBA", position: "PG", stat: "14.8 PPG", number: "4" },
  { name: "Markelle Fultz", team: "Orlando Magic", league: "NBA", position: "PG", stat: "10.4 PPG, 5.8 APG", number: "20" },
  { name: "Moritz Wagner", team: "Orlando Magic", league: "NBA", position: "C/PF", stat: "10.8 PPG", number: "21" },
  { name: "Gary Harris", team: "Orlando Magic", league: "NBA", position: "SG", stat: "8.4 PPG", number: "14" },
  // Philadelphia 76ers
  { name: "Joel Embiid", team: "Philadelphia 76ers", league: "NBA", position: "C", stat: "28.4 PPG, 11.4 REB", number: "21" },
  { name: "Tyrese Maxey", team: "Philadelphia 76ers", league: "NBA", position: "PG", stat: "26.1 PPG, 6.2 APG", number: "0" },
  { name: "Paul George", team: "Philadelphia 76ers", league: "NBA", position: "SF", stat: "18.8 PPG", number: "8" },
  { name: "Kelly Oubre Jr.", team: "Philadelphia 76ers", league: "NBA", position: "SF", stat: "14.8 PPG", number: "12" },
  { name: "André Drummond", team: "Philadelphia 76ers", league: "NBA", position: "C", stat: "9.4 PPG, 10.8 REB", number: "1" },
  // Phoenix Suns
  { name: "Devin Booker", team: "Phoenix Suns", league: "NBA", position: "SG", stat: "33.9 PPG (last 4 games)", number: "1" },
  { name: "Bradley Beal", team: "Phoenix Suns", league: "NBA", position: "SG", stat: "16.4 PPG", number: "3" },
  { name: "Jusuf Nurkić", team: "Phoenix Suns", league: "NBA", position: "C", stat: "12.8 PPG, 11.4 REB", number: "20" },
  { name: "Grayson Allen", team: "Phoenix Suns", league: "NBA", position: "SG", stat: "10.4 PPG", number: "7" },
  { name: "Drew Eubanks", team: "Phoenix Suns", league: "NBA", position: "C", stat: "8.4 PPG", number: "14" },
  // Portland Trail Blazers
  { name: "Scoot Henderson", team: "Portland Trail Blazers", league: "NBA", position: "PG", stat: "17.8 PPG, 6.4 APG", number: "00" },
  { name: "Anfernee Simons", team: "Portland Trail Blazers", league: "NBA", position: "SG", stat: "22.4 PPG", number: "1" },
  { name: "Jerami Grant", team: "Portland Trail Blazers", league: "NBA", position: "SF/PF", stat: "16.8 PPG", number: "9" },
  { name: "Deandre Ayton", team: "Portland Trail Blazers", league: "NBA", position: "C", stat: "14.8 PPG, 10.4 REB", number: "2" },
  { name: "Jabari Walker", team: "Portland Trail Blazers", league: "NBA", position: "PF", stat: "9.4 PPG", number: "34" },
  // Sacramento Kings
  { name: "De'Aaron Fox", team: "Sacramento Kings", league: "NBA", position: "PG", stat: "25.4 PPG, 6.2 APG", number: "5" },
  { name: "Domantas Sabonis", team: "Sacramento Kings", league: "NBA", position: "C/PF", stat: "20.8 PPG, 13.4 REB", number: "11" },
  { name: "Keegan Murray", team: "Sacramento Kings", league: "NBA", position: "SF/PF", stat: "18.4 PPG", number: "13" },
  { name: "Malik Monk", team: "Sacramento Kings", league: "NBA", position: "PG/SG", stat: "14.8 PPG", number: "0" },
  { name: "Kevin Huerter", team: "Sacramento Kings", league: "NBA", position: "SG/SF", stat: "11.4 PPG", number: "9" },
  // San Antonio Spurs
  { name: "Victor Wembanyama", team: "San Antonio Spurs", league: "NBA", position: "C/PF", stat: "28.4 PPG, 4.1 BLK", number: "1" },
  { name: "Devin Vassell", team: "San Antonio Spurs", league: "NBA", position: "SG/SF", stat: "18.4 PPG", number: "24" },
  { name: "Jeremy Sochan", team: "San Antonio Spurs", league: "NBA", position: "PF", stat: "14.4 PPG", number: "10" },
  { name: "Keldon Johnson", team: "San Antonio Spurs", league: "NBA", position: "SF", stat: "13.8 PPG", number: "3" },
  { name: "Chris Paul", team: "San Antonio Spurs", league: "NBA", position: "PG", stat: "8.4 PPG, 8.2 APG", number: "3" },
  { name: "Malaki Branham", team: "San Antonio Spurs", league: "NBA", position: "SG", stat: "10.4 PPG", number: "22" },
  { name: "Zach Collins", team: "San Antonio Spurs", league: "NBA", position: "C/PF", stat: "9.8 PPG", number: "23" },
  // Toronto Raptors
  { name: "Scottie Barnes", team: "Toronto Raptors", league: "NBA", position: "SF/PF", stat: "20.4 PPG, 8.8 REB", number: "4" },
  { name: "RJ Barrett", team: "Toronto Raptors", league: "NBA", position: "SG/SF", stat: "22.8 PPG", number: "9" },
  { name: "Jakob Poeltl", team: "Toronto Raptors", league: "NBA", position: "C", stat: "12.8 PPG, 9.4 REB", number: "25" },
  { name: "Immanuel Quickley", team: "Toronto Raptors", league: "NBA", position: "PG", stat: "18.4 PPG, 6.8 APG", number: "5" },
  { name: "Gradey Dick", team: "Toronto Raptors", league: "NBA", position: "SG", stat: "14.2 PPG", number: "1" },
  { name: "Chris Boucher", team: "Toronto Raptors", league: "NBA", position: "PF/C", stat: "9.8 PPG", number: "25" },
  // Utah Jazz
  { name: "Jordan Clarkson", team: "Utah Jazz", league: "NBA", position: "PG/SG", stat: "19.4 PPG, 6th Man Award winner", number: "00" },
  { name: "Lauri Markkanen", team: "Utah Jazz", league: "NBA", position: "PF", stat: "22.4 PPG, 8.8 REB", number: "23" },
  { name: "Collin Sexton", team: "Utah Jazz", league: "NBA", position: "PG/SG", stat: "16.8 PPG", number: "2" },
  { name: "John Collins", team: "Utah Jazz", league: "NBA", position: "PF/C", stat: "14.8 PPG, 7.2 REB", number: "20" },
  { name: "Kelly Olynyk", team: "Utah Jazz", league: "NBA", position: "C/PF", stat: "9.4 PPG", number: "41" },
  { name: "Keyonte George", team: "Utah Jazz", league: "NBA", position: "PG", stat: "14.4 PPG", number: "3" },
  { name: "Walker Kessler", team: "Utah Jazz", league: "NBA", position: "C", stat: "10.8 PPG, 9.4 REB, 2.4 BLK", number: "24" },
  { name: "Taylor Hendricks", team: "Utah Jazz", league: "NBA", position: "PF", stat: "8.8 PPG", number: "0" },
  // Washington Wizards
  { name: "Kyle Kuzma", team: "Washington Wizards", league: "NBA", position: "PF/SF", stat: "22.4 PPG, 8.4 REB", number: "33" },
  { name: "Bilal Coulibaly", team: "Washington Wizards", league: "NBA", position: "SF", stat: "14.8 PPG", number: "0" },
  { name: "Jordan Poole", team: "Washington Wizards", league: "NBA", position: "PG/SG", stat: "17.8 PPG", number: "13" },
  { name: "Deni Avdija", team: "Washington Wizards", league: "NBA", position: "SF/PF", stat: "16.4 PPG", number: "8" },
  { name: "Alexandre Sarr", team: "Washington Wizards", league: "NBA", position: "C/PF", stat: "12.4 PPG (rookie)", number: "20" },
  { name: "Corey Kispert", team: "Washington Wizards", league: "NBA", position: "SF", stat: "9.8 PPG", number: "24" },
];

// ─── ALL NFL PLAYERS ──────────────────────────────────────────────────────────
export const NFL_PLAYERS: SearchPlayer[] = [
  // Arizona Cardinals
  { name: "Kyler Murray", team: "Arizona Cardinals", league: "NFL", position: "QB", stat: "3,742 pass yds, 26 TD" },
  { name: "Marvin Harrison Jr.", team: "Arizona Cardinals", league: "NFL", position: "WR", stat: "1,248 rec yds, 10 TD" },
  { name: "James Conner", team: "Arizona Cardinals", league: "NFL", position: "RB", stat: "782 rush yds, 9 TD" },
  { name: "Trey McBride", team: "Arizona Cardinals", league: "NFL", position: "TE", stat: "84 rec, 892 yds" },
  { name: "Paris Johnson Jr.", team: "Arizona Cardinals", league: "NFL", position: "OT", stat: "Pro Bowl 2025" },
  // Atlanta Falcons
  { name: "Michael Penix Jr.", team: "Atlanta Falcons", league: "NFL", position: "QB", stat: "3,241 pass yds, 22 TD (starter)" },
  { name: "Bijan Robinson", team: "Atlanta Falcons", league: "NFL", position: "RB", stat: "1,189 rush yds, 11 TD" },
  { name: "Drake London", team: "Atlanta Falcons", league: "NFL", position: "WR", stat: "1,031 rec yds, 8 TD" },
  { name: "Kyle Pitts", team: "Atlanta Falcons", league: "NFL", position: "TE", stat: "68 rec, 784 yds" },
  { name: "Ra'Shaun Henry", team: "Atlanta Falcons", league: "NFL", position: "WR", stat: "624 rec yds" },
  // Baltimore Ravens
  { name: "Lamar Jackson", team: "Baltimore Ravens", league: "NFL", position: "QB", stat: "3,843 pass yds, 37 TD, 9 INT" },
  { name: "Derrick Henry", team: "Baltimore Ravens", league: "NFL", position: "RB", stat: "1,921 rush yds, 18 TD" },
  { name: "Zay Flowers", team: "Baltimore Ravens", league: "NFL", position: "WR", stat: "1,094 rec yds" },
  { name: "Mark Andrews", team: "Baltimore Ravens", league: "NFL", position: "TE", stat: "72 rec, 824 yds" },
  { name: "Roquan Smith", team: "Baltimore Ravens", league: "NFL", position: "LB", stat: "118 tackles, 3 INT" },
  { name: "Kyle Hamilton", team: "Baltimore Ravens", league: "NFL", position: "S", stat: "91 tackles, 4 INT" },
  // Buffalo Bills
  { name: "Josh Allen", team: "Buffalo Bills", league: "NFL", position: "QB", stat: "4,544 pass yds, 36 TD, 684 rush yds" },
  { name: "Khalil Shakir", team: "Buffalo Bills", league: "NFL", position: "WR", stat: "992 rec yds, 6 TD" },
  { name: "Dalton Kincaid", team: "Buffalo Bills", league: "NFL", position: "TE", stat: "684 rec yds, 5 TD" },
  { name: "James Cook", team: "Buffalo Bills", league: "NFL", position: "RB", stat: "1,009 rush yds, 8 TD" },
  { name: "Von Miller", team: "Buffalo Bills", league: "NFL", position: "EDGE", stat: "8.5 sacks" },
  { name: "Micah Hyde", team: "Buffalo Bills", league: "NFL", position: "S", stat: "68 tackles, 2 INT" },
  // Carolina Panthers
  { name: "Bryce Young", team: "Carolina Panthers", league: "NFL", position: "QB", stat: "3,124 pass yds, 18 TD" },
  { name: "Diontae Johnson", team: "Carolina Panthers", league: "NFL", position: "WR", stat: "782 rec yds" },
  { name: "Chuba Hubbard", team: "Carolina Panthers", league: "NFL", position: "RB", stat: "912 rush yds" },
  { name: "Brian Burns", team: "Carolina Panthers", league: "NFL", position: "EDGE", stat: "10.5 sacks" },
  // Chicago Bears
  { name: "Caleb Williams", team: "Chicago Bears", league: "NFL", position: "QB", stat: "3,541 pass yds, 24 TD" },
  { name: "D.J. Moore", team: "Chicago Bears", league: "NFL", position: "WR", stat: "1,084 rec yds" },
  { name: "Rome Odunze", team: "Chicago Bears", league: "NFL", position: "WR", stat: "892 rec yds (rookie)" },
  { name: "Cole Kmet", team: "Chicago Bears", league: "NFL", position: "TE", stat: "64 rec, 592 yds" },
  { name: "Montez Sweat", team: "Chicago Bears", league: "NFL", position: "EDGE", stat: "12.5 sacks" },
  // Cincinnati Bengals
  { name: "Joe Burrow", team: "Cincinnati Bengals", league: "NFL", position: "QB", stat: "4,284 pass yds, 33 TD" },
  { name: "Ja'Marr Chase", team: "Cincinnati Bengals", league: "NFL", position: "WR", stat: "1,708 rec yds, 14 TD" },
  { name: "Tee Higgins", team: "Cincinnati Bengals", league: "NFL", position: "WR", stat: "1,114 rec yds" },
  { name: "Evan McPherson", team: "Cincinnati Bengals", league: "NFL", position: "K", stat: "28/33 FG" },
  { name: "Trey Hendrickson", team: "Cincinnati Bengals", league: "NFL", position: "EDGE", stat: "17.5 sacks" },
  // Cleveland Browns
  { name: "Deshaun Watson", team: "Cleveland Browns", league: "NFL", position: "QB", stat: "Recovering from Achilles injury" },
  { name: "Nick Chubb", team: "Cleveland Browns", league: "NFL", position: "RB", stat: "892 rush yds (return from injury)" },
  { name: "Amari Cooper", team: "Cleveland Browns", league: "NFL", position: "WR", stat: "982 rec yds" },
  { name: "Myles Garrett", team: "Cleveland Browns", league: "NFL", position: "EDGE", stat: "16.0 sacks, DPOY candidate" },
  // Dallas Cowboys
  { name: "Dak Prescott", team: "Dallas Cowboys", league: "NFL", position: "QB", stat: "4,112 pass yds, 28 TD" },
  { name: "CeeDee Lamb", team: "Dallas Cowboys", league: "NFL", position: "WR", stat: "1,494 rec yds, 11 TD" },
  { name: "Jake Ferguson", team: "Dallas Cowboys", league: "NFL", position: "TE", stat: "84 rec, 892 yds" },
  { name: "Ezekiel Elliott", team: "Dallas Cowboys", league: "NFL", position: "RB", stat: "692 rush yds" },
  { name: "Micah Parsons", team: "Dallas Cowboys", league: "NFL", position: "LB/EDGE", stat: "14.5 sacks" },
  { name: "DaRon Bland", team: "Dallas Cowboys", league: "NFL", position: "CB", stat: "72 tackles, 4 INT" },
  // Denver Broncos
  { name: "Bo Nix", team: "Denver Broncos", league: "NFL", position: "QB", stat: "3,741 pass yds, 26 TD" },
  { name: "Jaylen Waddle", team: "Denver Broncos", league: "NFL", position: "WR", stat: "Traded from MIA" },
  { name: "Courtland Sutton", team: "Denver Broncos", league: "NFL", position: "WR", stat: "982 rec yds" },
  { name: "Javonte Williams", team: "Denver Broncos", league: "NFL", position: "RB", stat: "892 rush yds" },
  { name: "Patrick Surtain II", team: "Denver Broncos", league: "NFL", position: "CB", stat: "54 tackles, 6 INT" },
  // Detroit Lions
  { name: "Jared Goff", team: "Detroit Lions", league: "NFL", position: "QB", stat: "4,629 pass yds, 37 TD" },
  { name: "Amon-Ra St. Brown", team: "Detroit Lions", league: "NFL", position: "WR", stat: "1,294 rec yds, 12 TD" },
  { name: "Jameson Williams", team: "Detroit Lions", league: "NFL", position: "WR", stat: "1,082 rec yds" },
  { name: "Sam LaPorta", team: "Detroit Lions", league: "NFL", position: "TE", stat: "78 rec, 824 yds" },
  { name: "David Montgomery", team: "Detroit Lions", league: "NFL", position: "RB", stat: "1,124 rush yds" },
  { name: "Aidan Hutchinson", team: "Detroit Lions", league: "NFL", position: "EDGE", stat: "11.5 sacks (return from injury)" },
  // Green Bay Packers
  { name: "Jordan Love", team: "Green Bay Packers", league: "NFL", position: "QB", stat: "4,084 pass yds, 31 TD" },
  { name: "Jayden Reed", team: "Green Bay Packers", league: "NFL", position: "WR", stat: "1,084 rec yds" },
  { name: "Romeo Doubs", team: "Green Bay Packers", league: "NFL", position: "WR", stat: "924 rec yds" },
  { name: "Josh Jacobs", team: "Green Bay Packers", league: "NFL", position: "RB", stat: "1,124 rush yds" },
  { name: "Jaire Alexander", team: "Green Bay Packers", league: "NFL", position: "CB", stat: "54 tackles, 3 INT" },
  // Houston Texans
  { name: "C.J. Stroud", team: "Houston Texans", league: "NFL", position: "QB", stat: "4,108 pass yds, 28 TD" },
  { name: "Nico Collins", team: "Houston Texans", league: "NFL", position: "WR", stat: "1,297 rec yds, 9 TD" },
  { name: "Stefon Diggs", team: "Houston Texans", league: "NFL", position: "WR", stat: "1,024 rec yds" },
  { name: "Joe Mixon", team: "Houston Texans", league: "NFL", position: "RB", stat: "872 rush yds, 8 TD" },
  { name: "Will Anderson Jr.", team: "Houston Texans", league: "NFL", position: "EDGE", stat: "14.5 sacks" },
  { name: "Derek Stingley Jr.", team: "Houston Texans", league: "NFL", position: "CB", stat: "3 INT, 11 PD" },
  { name: "Dalton Schultz", team: "Houston Texans", league: "NFL", position: "TE", stat: "561 rec yds" },
  // Indianapolis Colts
  { name: "Anthony Richardson", team: "Indianapolis Colts", league: "NFL", position: "QB", stat: "2,984 pass yds, 18 TD" },
  { name: "Jonathan Taylor", team: "Indianapolis Colts", league: "NFL", position: "RB", stat: "1,124 rush yds, 10 TD" },
  { name: "Michael Pittman Jr.", team: "Indianapolis Colts", league: "NFL", position: "WR", stat: "1,084 rec yds" },
  { name: "DeForest Buckner", team: "Indianapolis Colts", league: "NFL", position: "DT", stat: "9 sacks" },
  // Jacksonville Jaguars
  { name: "Trevor Lawrence", team: "Jacksonville Jaguars", league: "NFL", position: "QB", stat: "3,741 pass yds, 24 TD" },
  { name: "Brian Thomas Jr.", team: "Jacksonville Jaguars", league: "NFL", position: "WR", stat: "992 rec yds (rookie)" },
  { name: "Travis Etienne Jr.", team: "Jacksonville Jaguars", league: "NFL", position: "RB", stat: "924 rush yds" },
  { name: "Josh Allen", team: "Jacksonville Jaguars", league: "NFL", position: "EDGE", stat: "13.5 sacks" },
  // Kansas City Chiefs
  { name: "Patrick Mahomes", team: "Kansas City Chiefs", league: "NFL", position: "QB", stat: "4,847 pass yds, 39 TD" },
  { name: "Travis Kelce", team: "Kansas City Chiefs", league: "NFL", position: "TE", stat: "1,054 rec yds, 7 TD" },
  { name: "Rashee Rice", team: "Kansas City Chiefs", league: "NFL", position: "WR", stat: "1,049 rec yds, 8 TD" },
  { name: "Kenneth Walker III", team: "Kansas City Chiefs", league: "NFL", position: "RB", stat: "1,069 rush yds, Super Bowl MVP" },
  { name: "Chris Jones", team: "Kansas City Chiefs", league: "NFL", position: "DT", stat: "11.0 sacks" },
  { name: "Trent McDuffie", team: "Kansas City Chiefs", league: "NFL", position: "CB", stat: "4 INT, 14 PD" },
  // Las Vegas Raiders
  { name: "Gardner Minshew", team: "Las Vegas Raiders", league: "NFL", position: "QB", stat: "2,841 pass yds, 16 TD" },
  { name: "Davante Adams", team: "Las Vegas Raiders", league: "NFL", position: "WR", stat: "1,024 rec yds" },
  { name: "Brock Bowers", team: "Las Vegas Raiders", league: "NFL", position: "TE", stat: "112 rec, 1,194 yds (rookie record)" },
  { name: "Maxx Crosby", team: "Las Vegas Raiders", league: "NFL", position: "EDGE", stat: "13.0 sacks" },
  // Los Angeles Chargers
  { name: "Justin Herbert", team: "Los Angeles Chargers", league: "NFL", position: "QB", stat: "4,384 pass yds, 33 TD" },
  { name: "Ladd McConkey", team: "Los Angeles Chargers", league: "NFL", position: "WR", stat: "1,082 rec yds (rookie)" },
  { name: "J.K. Dobbins", team: "Los Angeles Chargers", league: "NFL", position: "RB", stat: "1,001 rush yds" },
  { name: "Khalil Mack", team: "Los Angeles Chargers", league: "NFL", position: "EDGE", stat: "12.0 sacks" },
  // Los Angeles Rams
  { name: "Matthew Stafford", team: "Los Angeles Rams", league: "NFL", position: "QB", stat: "3,984 pass yds, 29 TD" },
  { name: "Cooper Kupp", team: "Los Angeles Rams", league: "NFL", position: "WR", stat: "1,024 rec yds" },
  { name: "Puka Nacua", team: "Los Angeles Rams", league: "NFL", position: "WR", stat: "1,184 rec yds" },
  { name: "Kyren Williams", team: "Los Angeles Rams", league: "NFL", position: "RB", stat: "1,189 rush yds" },
  { name: "Aaron Donald", team: "Los Angeles Rams", league: "NFL", position: "DT", stat: "Retired 2024" },
  { name: "Jalen Ramsey", team: "Los Angeles Rams", league: "NFL", position: "CB", stat: "62 tackles, 2 INT" },
  // Miami Dolphins
  { name: "Tua Tagovailoa", team: "Miami Dolphins", league: "NFL", position: "QB", stat: "3,241 pass yds, 23 TD" },
  { name: "Tyreek Hill", team: "Miami Dolphins", league: "NFL", position: "WR", stat: "1,184 rec yds" },
  { name: "De'Von Achane", team: "Miami Dolphins", league: "NFL", position: "RB", stat: "1,024 rush yds, 14 TD" },
  { name: "Jalen Ramsey", team: "Miami Dolphins", league: "NFL", position: "CB", stat: "Trade" },
  // Minnesota Vikings
  { name: "Sam Darnold", team: "Minnesota Vikings", league: "NFL", position: "QB", stat: "4,319 pass yds, 35 TD" },
  { name: "Justin Jefferson", team: "Minnesota Vikings", league: "NFL", position: "WR", stat: "1,512 rec yds, 10 TD" },
  { name: "Jordan Addison", team: "Minnesota Vikings", league: "NFL", position: "WR", stat: "1,024 rec yds" },
  { name: "T.J. Hockenson", team: "Minnesota Vikings", league: "NFL", position: "TE", stat: "72 rec, 784 yds" },
  { name: "Brian O'Neill", team: "Minnesota Vikings", league: "NFL", position: "OT", stat: "Pro Bowl 2025" },
  // New England Patriots
  { name: "Drake Maye", team: "New England Patriots", league: "NFL", position: "QB", stat: "2,874 pass yds, 18 TD (rookie)" },
  { name: "Kendrick Bourne", team: "New England Patriots", league: "NFL", position: "WR", stat: "684 rec yds" },
  { name: "Hunter Henry", team: "New England Patriots", league: "NFL", position: "TE", stat: "72 rec, 684 yds" },
  { name: "Matthew Judon", team: "New England Patriots", league: "NFL", position: "EDGE", stat: "10.5 sacks" },
  // New Orleans Saints
  { name: "Derek Carr", team: "New Orleans Saints", league: "NFL", position: "QB", stat: "2,984 pass yds, 19 TD" },
  { name: "Chris Olave", team: "New Orleans Saints", league: "NFL", position: "WR", stat: "1,124 rec yds" },
  { name: "Alvin Kamara", team: "New Orleans Saints", league: "NFL", position: "RB", stat: "892 rush yds, 6 TD" },
  { name: "Cameron Jordan", team: "New Orleans Saints", league: "NFL", position: "EDGE", stat: "9.5 sacks" },
  // New York Giants
  { name: "Daniel Jones", team: "New York Giants", league: "NFL", position: "QB", stat: "2,841 pass yds, 16 TD" },
  { name: "Malik Nabers", team: "New York Giants", league: "NFL", position: "WR", stat: "1,204 rec yds (rookie)" },
  { name: "Saquon Barkley", team: "New York Giants", league: "NFL", position: "RB", stat: "Signed with PHI" },
  { name: "Brian Burns", team: "New York Giants", league: "NFL", position: "EDGE", stat: "8.5 sacks" },
  // New York Jets
  { name: "Aaron Rodgers", team: "New York Jets", league: "NFL", position: "QB", stat: "3,124 pass yds, 22 TD (return)" },
  { name: "Garrett Wilson", team: "New York Jets", league: "NFL", position: "WR", stat: "1,084 rec yds" },
  { name: "Breece Hall", team: "New York Jets", league: "NFL", position: "RB", stat: "992 rush yds" },
  { name: "Will McDonald IV", team: "New York Jets", league: "NFL", position: "EDGE", stat: "10.0 sacks" },
  // Philadelphia Eagles
  { name: "Jalen Hurts", team: "Philadelphia Eagles", league: "NFL", position: "QB", stat: "3,988 pass yds, 31 TD, 712 rush yds" },
  { name: "A.J. Brown", team: "Philadelphia Eagles", league: "NFL", position: "WR", stat: "1,337 rec yds, 11 TD" },
  { name: "DeVonta Smith", team: "Philadelphia Eagles", league: "NFL", position: "WR", stat: "1,092 rec yds, 8 TD" },
  { name: "Saquon Barkley", team: "Philadelphia Eagles", league: "NFL", position: "RB", stat: "1,289 rush yds, 12 TD" },
  { name: "Dallas Goedert", team: "Philadelphia Eagles", league: "NFL", position: "TE", stat: "72 rec, 784 yds" },
  { name: "Haason Reddick", team: "Philadelphia Eagles", league: "NFL", position: "EDGE", stat: "12.5 sacks" },
  { name: "Darius Slay", team: "Philadelphia Eagles", league: "NFL", position: "CB", stat: "54 tackles, 2 INT" },
  // Pittsburgh Steelers
  { name: "Justin Fields", team: "Pittsburgh Steelers", league: "NFL", position: "QB", stat: "2,984 pass yds, 21 TD, 624 rush yds" },
  { name: "George Pickens", team: "Pittsburgh Steelers", league: "NFL", position: "WR", stat: "1,124 rec yds" },
  { name: "Najee Harris", team: "Pittsburgh Steelers", league: "NFL", position: "RB", stat: "892 rush yds" },
  { name: "T.J. Watt", team: "Pittsburgh Steelers", league: "NFL", position: "EDGE", stat: "19.0 sacks, DPOY" },
  { name: "Cam Heyward", team: "Pittsburgh Steelers", league: "NFL", position: "DT", stat: "8.5 sacks" },
  // San Francisco 49ers
  { name: "Brock Purdy", team: "San Francisco 49ers", league: "NFL", position: "QB", stat: "4,012 pass yds, 32 TD" },
  { name: "Deebo Samuel", team: "San Francisco 49ers", league: "NFL", position: "WR/RB", stat: "1,084 rec yds" },
  { name: "Brandon Aiyuk", team: "San Francisco 49ers", league: "NFL", position: "WR", stat: "1,294 rec yds" },
  { name: "Christian McCaffrey", team: "San Francisco 49ers", league: "NFL", position: "RB", stat: "1,689 rush yds, 17 TD" },
  { name: "George Kittle", team: "San Francisco 49ers", league: "NFL", position: "TE", stat: "1,124 rec yds" },
  { name: "Nick Bosa", team: "San Francisco 49ers", league: "NFL", position: "EDGE", stat: "14.5 sacks" },
  { name: "Fred Warner", team: "San Francisco 49ers", league: "NFL", position: "LB", stat: "124 tackles" },
  // Seattle Seahawks
  { name: "Geno Smith", team: "Seattle Seahawks", league: "NFL", position: "QB", stat: "3,484 pass yds, 24 TD" },
  { name: "DK Metcalf", team: "Seattle Seahawks", league: "NFL", position: "WR", stat: "1,294 rec yds" },
  { name: "Tyler Lockett", team: "Seattle Seahawks", league: "NFL", position: "WR", stat: "892 rec yds" },
  { name: "Kenneth Walker III", team: "Seattle Seahawks", league: "NFL", position: "RB", stat: "Traded to KC" },
  { name: "Bobby Wagner", team: "Seattle Seahawks", league: "NFL", position: "LB", stat: "138 tackles" },
  // Tampa Bay Buccaneers
  { name: "Baker Mayfield", team: "Tampa Bay Buccaneers", league: "NFL", position: "QB", stat: "4,084 pass yds, 32 TD" },
  { name: "Mike Evans", team: "Tampa Bay Buccaneers", league: "NFL", position: "WR", stat: "1,084 rec yds, 12 TD" },
  { name: "Chris Godwin", team: "Tampa Bay Buccaneers", league: "NFL", position: "WR", stat: "924 rec yds" },
  { name: "Rachaad White", team: "Tampa Bay Buccaneers", league: "NFL", position: "RB", stat: "1,024 rush yds" },
  { name: "Lavonte David", team: "Tampa Bay Buccaneers", league: "NFL", position: "LB", stat: "114 tackles" },
  // Tennessee Titans
  { name: "Will Levis", team: "Tennessee Titans", league: "NFL", position: "QB", stat: "3,124 pass yds, 22 TD" },
  { name: "DeAndre Hopkins", team: "Tennessee Titans", league: "NFL", position: "WR", stat: "892 rec yds" },
  { name: "Tony Pollard", team: "Tennessee Titans", league: "NFL", position: "RB", stat: "892 rush yds" },
  { name: "Harold Landry III", team: "Tennessee Titans", league: "NFL", position: "EDGE", stat: "10.0 sacks" },
  // Washington Commanders
  { name: "Jayden Daniels", team: "Washington Commanders", league: "NFL", position: "QB", stat: "3,568 pass yds, 25 TD, 891 rush yds (rookie)" },
  { name: "Terry McLaurin", team: "Washington Commanders", league: "NFL", position: "WR", stat: "1,084 rec yds" },
  { name: "Brian Robinson Jr.", team: "Washington Commanders", league: "NFL", position: "RB", stat: "1,024 rush yds" },
  { name: "Frankie Luvu", team: "Washington Commanders", league: "NFL", position: "LB/EDGE", stat: "10.5 sacks" },
];

// ─── ALL MLB PLAYERS ──────────────────────────────────────────────────────────
export const MLB_PLAYERS: SearchPlayer[] = [
  // Arizona Diamondbacks
  { name: "Corbin Carroll", team: "Arizona Diamondbacks", league: "MLB", position: "OF", stat: ".272 / 21 HR / 72 RBI" },
  { name: "Ketel Marte", team: "Arizona Diamondbacks", league: "MLB", position: "2B/OF", stat: ".291 / 26 HR / 88 RBI" },
  { name: "Lourdes Gurriel Jr.", team: "Arizona Diamondbacks", league: "MLB", position: "OF", stat: ".284 / 19 HR" },
  { name: "Merrill Kelly", team: "Arizona Diamondbacks", league: "MLB", position: "SP", stat: "14W, 3.89 ERA" },
  { name: "Zac Gallen", team: "Arizona Diamondbacks", league: "MLB", position: "SP", stat: "13W, 3.47 ERA" },
  // Atlanta Braves
  { name: "Ronald Acuña Jr.", team: "Atlanta Braves", league: "MLB", position: "OF", stat: ".294 / 34 HR / 88 RBI (injury return)" },
  { name: "Ozzie Albies", team: "Atlanta Braves", league: "MLB", position: "2B", stat: ".278 / 22 HR / 76 RBI" },
  { name: "Austin Riley", team: "Atlanta Braves", league: "MLB", position: "3B", stat: ".284 / 31 HR / 101 RBI" },
  { name: "Matt Olson", team: "Atlanta Braves", league: "MLB", position: "1B", stat: ".254 / 38 HR / 104 RBI" },
  { name: "Spencer Strider", team: "Atlanta Braves", league: "MLB", position: "SP", stat: "18W, 2.98 ERA, 281 SO (return)" },
  { name: "Chris Sale", team: "Atlanta Braves", league: "MLB", position: "SP", stat: "13W, 3.21 ERA" },
  { name: "Michael Harris II", team: "Atlanta Braves", league: "MLB", position: "OF", stat: ".276 / 24 HR" },
  // Baltimore Orioles
  { name: "Gunnar Henderson", team: "Baltimore Orioles", league: "MLB", position: "SS/3B", stat: ".291 / 36 HR / 99 RBI" },
  { name: "Adley Rutschman", team: "Baltimore Orioles", league: "MLB", position: "C", stat: ".264 / 18 HR / 72 RBI" },
  { name: "Anthony Santander", team: "Baltimore Orioles", league: "MLB", position: "OF", stat: ".271 / 44 HR / 102 RBI" },
  { name: "Jordan Westburg", team: "Baltimore Orioles", league: "MLB", position: "2B/3B", stat: ".278 / 24 HR" },
  { name: "Corbin Burnes", team: "Baltimore Orioles", league: "MLB", position: "SP", stat: "15W, 2.92 ERA" },
  // Boston Red Sox
  { name: "Rafael Devers", team: "Boston Red Sox", league: "MLB", position: "3B", stat: ".274 / 38 HR / 99 RBI" },
  { name: "Triston Casas", team: "Boston Red Sox", league: "MLB", position: "1B", stat: ".264 / 24 HR" },
  { name: "Jarren Duran", team: "Boston Red Sox", league: "MLB", position: "OF", stat: ".289 / 22 HR, 42 SB" },
  { name: "Masataka Yoshida", team: "Boston Red Sox", league: "MLB", position: "OF/DH", stat: ".288 / 18 HR" },
  { name: "Brayan Bello", team: "Boston Red Sox", league: "MLB", position: "SP", stat: "12W, 3.84 ERA" },
  { name: "Garrett Whitlock", team: "Boston Red Sox", league: "MLB", position: "SP/RP", stat: "3.24 ERA" },
  // Chicago Cubs
  { name: "Seiya Suzuki", team: "Chicago Cubs", league: "MLB", position: "OF", stat: ".281 / 28 HR / 84 RBI" },
  { name: "Dansby Swanson", team: "Chicago Cubs", league: "MLB", position: "SS", stat: ".258 / 20 HR / 74 RBI" },
  { name: "Ian Happ", team: "Chicago Cubs", league: "MLB", position: "OF", stat: ".241 / 21 HR" },
  { name: "Cody Bellinger", team: "Chicago Cubs", league: "MLB", position: "OF/1B", stat: ".284 / 26 HR" },
  { name: "Kyle Hendricks", team: "Chicago Cubs", league: "MLB", position: "SP", stat: "9W, 4.12 ERA" },
  { name: "Jameson Taillon", team: "Chicago Cubs", league: "MLB", position: "SP", stat: "12W, 3.96 ERA" },
  // Chicago White Sox
  { name: "Luis Robert Jr.", team: "Chicago White Sox", league: "MLB", position: "OF", stat: ".276 / 29 HR (injury return)" },
  { name: "Andrew Vaughn", team: "Chicago White Sox", league: "MLB", position: "OF/1B", stat: ".261 / 18 HR" },
  { name: "Garrett Crochet", team: "Chicago White Sox", league: "MLB", position: "SP", stat: "6W, 3.28 ERA, 212 SO" },
  { name: "Colson Montgomery", team: "Chicago White Sox", league: "MLB", position: "SS", stat: ".244 / 14 HR (prospect)" },
  // Cincinnati Reds
  { name: "Elly De La Cruz", team: "Cincinnati Reds", league: "MLB", position: "SS", stat: ".278 / 28 HR, 40 SB" },
  { name: "Hunter Greene", team: "Cincinnati Reds", league: "MLB", position: "SP", stat: "13W, 3.74 ERA, 224 SO" },
  { name: "TJ Friedl", team: "Cincinnati Reds", league: "MLB", position: "OF", stat: ".274 / 18 HR, 28 SB" },
  { name: "Tyler Stephenson", team: "Cincinnati Reds", league: "MLB", position: "C", stat: ".274 / 16 HR" },
  { name: "Jonathan India", team: "Cincinnati Reds", league: "MLB", position: "2B", stat: ".262 / 14 HR" },
  // Cleveland Guardians
  { name: "José Ramírez", team: "Cleveland Guardians", league: "MLB", position: "3B", stat: ".282 / 34 HR / 103 RBI" },
  { name: "Steven Kwan", team: "Cleveland Guardians", league: "MLB", position: "OF", stat: ".289 / 12 HR / 58 RBI" },
  { name: "Josh Naylor", team: "Cleveland Guardians", league: "MLB", position: "1B", stat: ".274 / 24 HR / 88 RBI" },
  { name: "Shane Bieber", team: "Cleveland Guardians", league: "MLB", position: "SP", stat: "12W, 3.24 ERA (return)" },
  { name: "Triston McKenzie", team: "Cleveland Guardians", league: "MLB", position: "SP", stat: "11W, 3.84 ERA" },
  // Colorado Rockies
  { name: "Charlie Blackmon", team: "Colorado Rockies", league: "MLB", position: "OF", stat: ".264 / 16 HR" },
  { name: "C.J. Cron", team: "Colorado Rockies", league: "MLB", position: "1B", stat: ".248 / 24 HR" },
  { name: "Kyle Freeland", team: "Colorado Rockies", league: "MLB", position: "SP", stat: "8W, 4.84 ERA" },
  // Detroit Tigers
  { name: "Kerry Carpenter", team: "Detroit Tigers", league: "MLB", position: "OF/DH", stat: ".271 / 24 HR" },
  { name: "Spencer Torkelson", team: "Detroit Tigers", league: "MLB", position: "1B", stat: ".261 / 22 HR" },
  { name: "Tarik Skubal", team: "Detroit Tigers", league: "MLB", position: "SP", stat: "19W, 2.39 ERA, 228 SO — Cy Young" },
  { name: "Jack Flaherty", team: "Detroit Tigers", league: "MLB", position: "SP", stat: "13W, 3.84 ERA" },
  { name: "Javier Báez", team: "Detroit Tigers", league: "MLB", position: "SS", stat: ".248 / 18 HR" },
  // Houston Astros
  { name: "Yordan Alvarez", team: "Houston Astros", league: "MLB", position: "DH/LF", stat: ".291 / 39 HR / 109 RBI" },
  { name: "José Altuve", team: "Houston Astros", league: "MLB", position: "2B", stat: ".281 / 18 HR" },
  { name: "Alex Bregman", team: "Houston Astros", league: "MLB", position: "3B", stat: ".268 / 24 HR / 87 RBI" },
  { name: "Kyle Tucker", team: "Houston Astros", league: "MLB", position: "RF", stat: ".276 / 29 HR / 96 RBI" },
  { name: "Jeremy Peña", team: "Houston Astros", league: "MLB", position: "SS", stat: ".256 / 17 HR" },
  { name: "Framber Valdez", team: "Houston Astros", league: "MLB", position: "SP", stat: "17W, 2.81 ERA" },
  { name: "Ronel Blanco", team: "Houston Astros", league: "MLB", position: "SP", stat: "14W, 3.10 ERA" },
  { name: "Ryan Pressly", team: "Houston Astros", league: "MLB", position: "RP/CL", stat: "28 SV, 2.99 ERA" },
  // Kansas City Royals
  { name: "Bobby Witt Jr.", team: "Kansas City Royals", league: "MLB", position: "SS", stat: ".294 / 32 HR / 97 RBI" },
  { name: "Vinnie Pasquantino", team: "Kansas City Royals", league: "MLB", position: "1B", stat: ".279 / 22 HR" },
  { name: "Salvador Perez", team: "Kansas City Royals", league: "MLB", position: "C", stat: ".271 / 28 HR / 84 RBI" },
  { name: "Cole Ragans", team: "Kansas City Royals", league: "MLB", position: "SP", stat: "14W, 3.14 ERA" },
  // Los Angeles Angels
  { name: "Mike Trout", team: "Los Angeles Angels", league: "MLB", position: "OF", stat: ".280 / 31 HR (injury return)" },
  { name: "Shohei Ohtani", team: "Los Angeles Dodgers", league: "MLB", position: "DH/SP", stat: "Signed with Dodgers" },
  { name: "Logan O'Hoppe", team: "Los Angeles Angels", league: "MLB", position: "C", stat: ".261 / 18 HR" },
  { name: "Reid Detmers", team: "Los Angeles Angels", league: "MLB", position: "SP", stat: "10W, 3.94 ERA" },
  // Los Angeles Dodgers
  { name: "Shohei Ohtani", team: "Los Angeles Dodgers", league: "MLB", position: "DH", stat: ".307 / 44 HR / 124 RBI" },
  { name: "Freddie Freeman", team: "Los Angeles Dodgers", league: "MLB", position: "1B", stat: ".296 / 26 HR / 99 RBI" },
  { name: "Mookie Betts", team: "Los Angeles Dodgers", league: "MLB", position: "SS/OF", stat: ".288 / 28 HR" },
  { name: "Teoscar Hernández", team: "Los Angeles Dodgers", league: "MLB", position: "OF", stat: ".274 / 34 HR / 104 RBI" },
  { name: "Tyler Glasnow", team: "Los Angeles Dodgers", league: "MLB", position: "SP", stat: "16W, 3.00 ERA" },
  { name: "Yoshinobu Yamamoto", team: "Los Angeles Dodgers", league: "MLB", position: "SP", stat: "17W, 2.86 ERA (return)" },
  { name: "Clayton Kershaw", team: "Los Angeles Dodgers", league: "MLB", position: "SP", stat: "Retired 2024" },
  { name: "Will Smith", team: "Los Angeles Dodgers", league: "MLB", position: "C", stat: ".251 / 19 HR" },
  // Miami Marlins
  { name: "Jazz Chisholm Jr.", team: "Miami Marlins", league: "MLB", position: "CF", stat: ".261 / 22 HR, 24 SB" },
  { name: "Luis Arraez", team: "Miami Marlins", league: "MLB", position: "2B", stat: ".318 / 4 HR — batting title candidate" },
  { name: "Sandy Alcantara", team: "Miami Marlins", league: "MLB", position: "SP", stat: "12W, 3.24 ERA (return)" },
  // Milwaukee Brewers
  { name: "Willy Adames", team: "Milwaukee Brewers", league: "MLB", position: "SS", stat: ".258 / 28 HR / 84 RBI" },
  { name: "Christian Yelich", team: "Milwaukee Brewers", league: "MLB", position: "OF", stat: ".274 / 22 HR" },
  { name: "Sal Frelick", team: "Milwaukee Brewers", league: "MLB", position: "OF", stat: ".281 / 14 HR" },
  { name: "Freddy Peralta", team: "Milwaukee Brewers", league: "MLB", position: "SP", stat: "14W, 3.24 ERA" },
  { name: "Devin Williams", team: "Milwaukee Brewers", league: "MLB", position: "RP/CL", stat: "31 SV, 2.14 ERA" },
  // Minnesota Twins
  { name: "Carlos Correa", team: "Minnesota Twins", league: "MLB", position: "SS", stat: ".278 / 22 HR / 79 RBI" },
  { name: "Byron Buxton", team: "Minnesota Twins", league: "MLB", position: "CF", stat: ".274 / 28 HR" },
  { name: "Ryan Jeffers", team: "Minnesota Twins", league: "MLB", position: "C", stat: ".268 / 21 HR" },
  { name: "Pablo López", team: "Minnesota Twins", league: "MLB", position: "SP", stat: "15W, 3.24 ERA" },
  { name: "Joe Ryan", team: "Minnesota Twins", league: "MLB", position: "SP", stat: "12W, 3.74 ERA" },
  // New York Mets
  { name: "Francisco Lindor", team: "New York Mets", league: "MLB", position: "SS", stat: ".274 / 34 HR / 104 RBI" },
  { name: "Pete Alonso", team: "New York Mets", league: "MLB", position: "1B", stat: ".256 / 44 HR / 124 RBI" },
  { name: "Mark Vientos", team: "New York Mets", league: "MLB", position: "3B", stat: ".271 / 28 HR" },
  { name: "Kodai Senga", team: "New York Mets", league: "MLB", position: "SP", stat: "11W, 3.14 ERA (return)" },
  { name: "Sean Manaea", team: "New York Mets", league: "MLB", position: "SP", stat: "12W, 3.44 ERA" },
  // New York Yankees
  { name: "Aaron Judge", team: "New York Yankees", league: "MLB", position: "RF", stat: ".295 / 48 HR / 124 RBI — AL MVP" },
  { name: "Juan Soto", team: "New York Yankees", league: "MLB", position: "LF", stat: ".288 / 34 HR / 99 RBI" },
  { name: "Giancarlo Stanton", team: "New York Yankees", league: "MLB", position: "DH", stat: ".248 / 31 HR" },
  { name: "Gerrit Cole", team: "New York Yankees", league: "MLB", position: "SP", stat: "TJS return — Spring 2026" },
  { name: "Clay Holmes", team: "New York Yankees", league: "MLB", position: "RP/CL", stat: "32 SV, 3.14 ERA" },
  { name: "Anthony Volpe", team: "New York Yankees", league: "MLB", position: "SS", stat: ".261 / 18 HR" },
  { name: "Jazz Chisholm Jr.", team: "New York Yankees", league: "MLB", position: "3B", stat: "Traded to Yanks mid-season" },
  // Oakland Athletics
  { name: "Brent Rooker", team: "Oakland Athletics", league: "MLB", position: "OF/DH", stat: ".281 / 34 HR / 99 RBI" },
  { name: "Shea Langeliers", team: "Oakland Athletics", league: "MLB", position: "C", stat: ".241 / 28 HR" },
  { name: "Mason Miller", team: "Oakland Athletics", league: "MLB", position: "RP/CL", stat: "29 SV, 1.84 ERA" },
  { name: "JP Sears", team: "Oakland Athletics", league: "MLB", position: "SP", stat: "12W, 3.94 ERA" },
  // Philadelphia Phillies
  { name: "Bryce Harper", team: "Philadelphia Phillies", league: "MLB", position: "1B", stat: ".286 / 34 HR / 104 RBI" },
  { name: "Kyle Schwarber", team: "Philadelphia Phillies", league: "MLB", position: "LF", stat: ".221 / 44 HR / 96 RBI" },
  { name: "Trea Turner", team: "Philadelphia Phillies", league: "MLB", position: "SS", stat: ".271 / 24 HR, 28 SB" },
  { name: "Zack Wheeler", team: "Philadelphia Phillies", league: "MLB", position: "SP", stat: "17W, 2.74 ERA" },
  { name: "Aaron Nola", team: "Philadelphia Phillies", league: "MLB", position: "SP", stat: "14W, 3.24 ERA" },
  { name: "Ranger Suárez", team: "Philadelphia Phillies", league: "MLB", position: "SP", stat: "12W, 3.54 ERA" },
  { name: "Nick Castellanos", team: "Philadelphia Phillies", league: "MLB", position: "RF", stat: ".271 / 19 HR" },
  // Pittsburgh Pirates
  { name: "Paul Skenes", team: "Pittsburgh Pirates", league: "MLB", position: "SP", stat: "11W, 2.14 ERA — NL ROY" },
  { name: "Oneil Cruz", team: "Pittsburgh Pirates", league: "MLB", position: "SS", stat: ".248 / 22 HR, 28 SB" },
  { name: "Andrew McCutchen", team: "Pittsburgh Pirates", league: "MLB", position: "DH", stat: ".261 / 16 HR" },
  { name: "Bryan Reynolds", team: "Pittsburgh Pirates", league: "MLB", position: "OF", stat: ".271 / 22 HR" },
  // San Diego Padres
  { name: "Fernando Tatis Jr.", team: "San Diego Padres", league: "MLB", position: "RF", stat: ".281 / 38 HR / 96 RBI" },
  { name: "Manny Machado", team: "San Diego Padres", league: "MLB", position: "3B", stat: ".271 / 28 HR / 86 RBI" },
  { name: "Xander Bogaerts", team: "San Diego Padres", league: "MLB", position: "SS", stat: ".268 / 16 HR" },
  { name: "Jake Cronenworth", team: "San Diego Padres", league: "MLB", position: "1B/2B", stat: ".268 / 18 HR" },
  { name: "Dylan Cease", team: "San Diego Padres", league: "MLB", position: "SP", stat: "16W, 3.14 ERA" },
  { name: "Yu Darvish", team: "San Diego Padres", league: "MLB", position: "SP", stat: "11W, 3.74 ERA" },
  // San Francisco Giants
  { name: "Matt Chapman", team: "San Francisco Giants", league: "MLB", position: "3B", stat: ".261 / 29 HR" },
  { name: "LaMonte Wade Jr.", team: "San Francisco Giants", league: "MLB", position: "1B", stat: ".264 / 22 HR" },
  { name: "Logan Webb", team: "San Francisco Giants", league: "MLB", position: "SP", stat: "14W, 3.28 ERA" },
  { name: "Robbie Ray", team: "San Francisco Giants", league: "MLB", position: "SP", stat: "11W, 3.74 ERA" },
  // Seattle Mariners
  { name: "Julio Rodríguez", team: "Seattle Mariners", league: "MLB", position: "CF", stat: ".284 / 31 HR, 28 SB" },
  { name: "Cal Raleigh", team: "Seattle Mariners", league: "MLB", position: "C", stat: ".241 / 38 HR / 97 RBI" },
  { name: "Ty France", team: "Seattle Mariners", league: "MLB", position: "1B/DH", stat: ".264 / 18 HR" },
  { name: "Luis Castillo", team: "Seattle Mariners", league: "MLB", position: "SP", stat: "16W, 3.02 ERA" },
  { name: "Logan Gilbert", team: "Seattle Mariners", league: "MLB", position: "SP", stat: "15W, 3.14 ERA" },
  { name: "George Kirby", team: "Seattle Mariners", league: "MLB", position: "SP", stat: "14W, 3.44 ERA" },
  // St. Louis Cardinals
  { name: "Nolan Arenado", team: "St. Louis Cardinals", league: "MLB", position: "3B", stat: ".264 / 24 HR / 79 RBI" },
  { name: "Paul Goldschmidt", team: "St. Louis Cardinals", league: "MLB", position: "1B", stat: ".268 / 22 HR / 81 RBI" },
  { name: "Lars Nootbaar", team: "St. Louis Cardinals", league: "MLB", position: "OF", stat: ".274 / 18 HR" },
  { name: "Miles Mikolas", team: "St. Louis Cardinals", league: "MLB", position: "SP", stat: "10W, 3.98 ERA" },
  // Tampa Bay Rays
  { name: "Randy Arozarena", team: "Tampa Bay Rays", league: "MLB", position: "OF", stat: ".262 / 28 HR" },
  { name: "Yandy Díaz", team: "Tampa Bay Rays", league: "MLB", position: "1B/3B", stat: ".279 / 14 HR" },
  { name: "Shane McClanahan", team: "Tampa Bay Rays", league: "MLB", position: "SP", stat: "14W, 2.94 ERA" },
  { name: "Taj Bradley", team: "Tampa Bay Rays", league: "MLB", position: "SP", stat: "11W, 3.54 ERA" },
  // Texas Rangers
  { name: "Corey Seager", team: "Texas Rangers", league: "MLB", position: "SS", stat: ".291 / 31 HR / 93 RBI" },
  { name: "Marcus Semien", team: "Texas Rangers", league: "MLB", position: "2B", stat: ".258 / 22 HR / 71 RBI" },
  { name: "Adolis García", team: "Texas Rangers", league: "MLB", position: "RF", stat: ".264 / 31 HR / 93 RBI" },
  { name: "Nathaniel Lowe", team: "Texas Rangers", league: "MLB", position: "1B", stat: ".274 / 18 HR" },
  { name: "Max Scherzer", team: "Texas Rangers", league: "MLB", position: "SP", stat: "Retired 2024" },
  { name: "Tyler Mahle", team: "Texas Rangers", league: "MLB", position: "SP", stat: "12W, 3.84 ERA" },
  // Toronto Blue Jays
  { name: "Vladimir Guerrero Jr.", team: "Toronto Blue Jays", league: "MLB", position: "1B", stat: ".284 / 38 HR / 113 RBI" },
  { name: "Bo Bichette", team: "Toronto Blue Jays", league: "MLB", position: "SS", stat: ".276 / 21 HR" },
  { name: "George Springer", team: "Toronto Blue Jays", league: "MLB", position: "OF", stat: ".261 / 24 HR" },
  { name: "Kevin Gausman", team: "Toronto Blue Jays", league: "MLB", position: "SP", stat: "15W, 3.14 ERA" },
  { name: "José Berríos", team: "Toronto Blue Jays", league: "MLB", position: "SP", stat: "12W, 3.94 ERA" },
  // Washington Nationals
  { name: "CJ Abrams", team: "Washington Nationals", league: "MLB", position: "SS", stat: ".271 / 22 HR, 28 SB" },
  { name: "James Wood", team: "Washington Nationals", league: "MLB", position: "OF", stat: ".264 / 18 HR (prospect)" },
  { name: "MacKenzie Gore", team: "Washington Nationals", league: "MLB", position: "SP", stat: "11W, 3.64 ERA" },
  { name: "Patrick Corbin", team: "Washington Nationals", league: "MLB", position: "SP", stat: "7W, 5.12 ERA" },
];

// ─── KEY MLS PLAYERS ──────────────────────────────────────────────────────────
export const MLS_PLAYERS: SearchPlayer[] = [
  { name: "Lionel Messi", team: "Inter Miami CF", league: "MLS", position: "RW", stat: "22 goals, 16 assists" },
  { name: "Sergio Busquets", team: "Inter Miami CF", league: "MLS", position: "CM", stat: "3 goals, 12 assists" },
  { name: "Jordi Alba", team: "Inter Miami CF", league: "MLS", position: "LB", stat: "1 goal, 14 assists" },
  { name: "Josef Martinez", team: "Inter Miami CF", league: "MLS", position: "FW", stat: "14 goals" },
  { name: "Riqui Puig", team: "LA Galaxy", league: "MLS", position: "CM", stat: "12 goals, 14 assists" },
  { name: "Gabriel Pec", team: "LA Galaxy", league: "MLS", position: "RW", stat: "14 goals, 8 assists" },
  { name: "Dejan Joveljić", team: "LA Galaxy", league: "MLS", position: "ST", stat: "11 goals" },
  { name: "Cucho Hernandez", team: "Columbus Crew", league: "MLS", position: "FW", stat: "18 goals, 8 assists" },
  { name: "Luciano Acosta", team: "FC Cincinnati", league: "MLS", position: "AM", stat: "14 goals, 16 assists" },
  { name: "Xherdan Shaqiri", team: "Chicago Fire", league: "MLS", position: "RW", stat: "8 goals, 10 assists" },
  { name: "Petar Musa", team: "Vancouver Whitecaps", league: "MLS", position: "ST", stat: "5 goals — league leader" },
  { name: "Brian White", team: "Vancouver Whitecaps", league: "MLS", position: "ST", stat: "12 goals" },
  { name: "Caden Clark", team: "New England Revolution", league: "MLS", position: "MF", stat: "8 goals, 6 assists" },
  { name: "Ricardo Pepi", team: "Houston Dynamo", league: "MLS", position: "ST", stat: "11 goals" },
  { name: "Ezequiel Ponce", team: "Houston Dynamo", league: "MLS", position: "FW", stat: "7 goals, 3 assists" },
  { name: "Adalberto Carrasquilla", team: "Houston Dynamo", league: "MLS", position: "CM", stat: "3 goals, 7 assists" },
  { name: "Carlos Vela", team: "Los Angeles FC", league: "MLS", position: "FW", stat: "9 goals, 7 assists" },
  { name: "Denis Bouanga", team: "Los Angeles FC", league: "MLS", position: "LW", stat: "17 goals" },
  { name: "Cristian Arango", team: "Real Salt Lake", league: "MLS", position: "ST", stat: "14 goals" },
  { name: "Giorgos Giakoumakis", team: "Atlanta United", league: "MLS", position: "ST", stat: "16 goals" },
  { name: "Aaron Herrera", team: "New York Red Bulls", league: "MLS", position: "RB", stat: "3 goals, 8 assists" },
  { name: "DJ Taylor", team: "Nashville SC", league: "MLS", position: "FW", stat: "10 goals" },
  { name: "Walker Zimmerman", team: "Nashville SC", league: "MLS", position: "CB", stat: "USMNT captain" },
  { name: "Ike Opara", team: "Sporting Kansas City", league: "MLS", position: "CB", stat: "Team captain" },
  { name: "Alan Pulido", team: "Sporting Kansas City", league: "MLS", position: "FW", stat: "9 goals" },
  { name: "Ryan Gauld", team: "Vancouver Whitecaps", league: "MLS", position: "AM", stat: "6 goals, 12 assists" },
  { name: "Jhon Durán", team: "Chicago Fire", league: "MLS", position: "ST", stat: "12 goals" },
  { name: "Cyle Larin", team: "Columbus Crew", league: "MLS", position: "FW", stat: "14 goals" },
  { name: "Dom Dwyer", team: "Orlando City", league: "MLS", position: "FW", stat: "9 goals" },
  { name: "Folarin Balogun", team: "D.C. United", league: "MLS", position: "ST", stat: "11 goals" },
];

export const ALL_PLAYERS: SearchPlayer[] = [
  ...NBA_PLAYERS,
  ...NFL_PLAYERS,
  ...MLB_PLAYERS,
  ...MLS_PLAYERS,
];
