export const SPORTS = [
  { id: "NFL", label: "NFL", icon: "football", color: "#013087" },
  { id: "NBA", label: "NBA", icon: "basketball", color: "#C9082A" },
  { id: "MLB", label: "MLB", icon: "baseball", color: "#002D72" },
  { id: "MLS", label: "MLS", icon: "football", color: "#1A1A2E" },
  { id: "UFC", label: "UFC", icon: "fitness", color: "#D20A0A" },
  { id: "NHL", label: "NHL", icon: "snow", color: "#0038A8" },
];

export const TEAMS_BY_LEAGUE: Record<string, string[]> = {
  NFL: [
    "Kansas City Chiefs",
    "Buffalo Bills",
    "San Francisco 49ers",
    "Dallas Cowboys",
    "Philadelphia Eagles",
    "Baltimore Ravens",
    "Miami Dolphins",
    "Detroit Lions",
    "Houston Texans",
    "Los Angeles Rams",
    "Cincinnati Bengals",
    "New England Patriots",
  ],
  NBA: [
    "Houston Rockets",
    "Golden State Warriors",
    "Los Angeles Lakers",
    "Boston Celtics",
    "Miami Heat",
    "Denver Nuggets",
    "Phoenix Suns",
    "Milwaukee Bucks",
    "Dallas Mavericks",
    "Oklahoma City Thunder",
    "Minnesota Timberwolves",
    "New York Knicks",
  ],
  MLB: [
    "Houston Astros",
    "New York Yankees",
    "Los Angeles Dodgers",
    "Atlanta Braves",
    "Texas Rangers",
    "Boston Red Sox",
    "Chicago Cubs",
    "San Diego Padres",
    "Toronto Blue Jays",
    "Chicago White Sox",
    "Seattle Mariners",
    "Tampa Bay Rays",
  ],
  MLS: [
    "Inter Miami",
    "LA Galaxy",
    "Atlanta United",
    "NYCFC",
    "Seattle Sounders",
    "Portland Timbers",
    "Austin FC",
    "Charlotte FC",
  ],
  UFC: [],
  NHL: [
    "Vegas Golden Knights",
    "Boston Bruins",
    "Colorado Avalanche",
    "New York Rangers",
    "Toronto Maple Leafs",
    "Carolina Hurricanes",
    "Edmonton Oilers",
    "Florida Panthers",
  ],
};

export const LEAGUE_COLORS: Record<string, string> = {
  NFL: "#013087",
  NBA: "#C9082A",
  MLB: "#002D72",
  MLS: "#3A7D2C",
  UFC: "#D20A0A",
  NHL: "#0038A8",
};
